### ISSUE TITLE
Integration with RL4CO

### ISSUE THREAD

**Issue by fedebotu** [henry-yeh/DeepACO#2]
Hi there 👋🏼 
Great job with your paper and library! 
We are actively developing [RL4CO](https://github.com/kaist-silab/rl4co), a library for all things Reinforcement Learning for Combinatorial Optimization. We would like to include your work as well in the library; after inspecting the code, we got several ideas on how to modularize DeepACO.
If you would like to contribute to RL4CO, feel free to contact us - perhaps via [Slack](https://join.slack.com/t/rl4co/shared_invite/zt-1ytz2c1v4-0IkQ8NQH4TRXIX8PrRmDhQ) - or by submitting issues or PRs.
Looking forward for your poster at NeurIPS ;)

**Comment by henry-yeh** [comment]
Hey 👋🏼

Thank you for your kind acknowledgement and for reaching out to us. RL4CO is a fantastic library, and we are both interested and honored to have the opportunity to contribute to it 🤩.
