### ISSUE TITLE
mkp问题的验证集

### ISSUE THREAD

**Issue by Boaty30** [henry-yeh/DeepACO#4]
你好！因为我想试图针对自己的优化算法构建验证集，但是我不知道该怎么做，不过我似乎没有在/data文件夹下面看到mkp问题的相应的验证集。（可能是我读代码有遗漏？）
总之，希望能得到你的回复，many thx！

**Comment by Boaty30** [comment]
emmm原来真的是我读代码有遗漏哈哈

**Comment by henry-yeh** [comment]
您好，感谢兴趣！抱歉代码不清楚，在mkp/utils.py应该可以找到！

**Comment by Boaty30** [comment]
确实，我已经发现了，感谢您的耐心！我正准备尝试利用您论文的思路在模拟退火算法上做尝试，想请教一下您是否具有可行性。

**Comment by henry-yeh** [comment]
当然，思路是通用的，可能有类似工作：https://arxiv.org/pdf/2203.02201.pdf
